### ISSUE TITLE
On Ubuntu, cert.pem and key.pem are created as directories

### ISSUE THREAD

**Issue by bballamudi** [alexisrolland/docker-openssl#3]
I followed your instructions for setting up the docker image for mobydq [here](https://ubisoft.github.io/mobydq/pages/gettingstarted/).

### Observed:

docker run -it --rm -v "/<your_path>/mobydq/nginx/config:/openssl-certs" docker-openssl

On Ubuntu when I run the above command it generates folders under /mobydq/nginx/config named cert.pem and key.pem. As a result getting the following error.

```
OpenSSL> req -x509 -newkey rsa:4096 -nodes -out cert.pem -keyout key.pem -days 365
Generating a RSA private key
..................................................................................................................................................................................++++
...........................++++
writing new private key to 'key.pem'
req: Can't open "key.pem" for writing, Is a directory
error in req
```

### Expected:
The command is supposed to create cert.pem and key.pem as files instead. Unless I am missing something.

**Comment by alexisrolland** [comment]
Hi @bballamudi 

When running the Docker container, could you please confirm whether you mounted a correct folder path? In the example you provided above you still have ‘<your_path>’ in the folder path. You need to replace that to have a complete folder path.

If you still have the issue with a correct folder path, make sure you delete the cert.pem and key.pem, remove de Docker container, shut down Docker, restart it and retry the process... I have ran it many times without trouble.

Let me know How it goes.
Thanks
Alexis

**Comment by bballamudi** [comment]
@alexisrolland I believe I've mounted the correct folder path as it is validated by the fact that I see those cert.pem and key.pem folders getting created in the said folder path. 
However, these are folders and not files to be edited and hence the issue. 

I've destroyed and rebuild the docker images still the issue persists. I've however not restarted the Docker itself. I might as well try that will get back to you.

But is there any reason why I've got those created as folders instead of files?

**Comment by bballamudi** [comment]
The issue still persists.
I have got around those by manually installing those keys and now I don't see those issues.

However, now I encounter another set of errors related to the database.
I only get one error with regard to mobydq-graphql captured in the picture below.

![image](https://user-images.githubusercontent.com/21183667/89205410-501e1b00-d57d-11ea-8a8b-8581feb45705.png)

I've created an RDS instance in AWS of type Postgres and replaced the command '\create mobydq with \create a-functional-postgres-RDS'. I replaced with the correct string at other relevant places as well.

Could you help me figure out the issue?

**Comment by alexisrolland** [comment]
Hello @bballamudi 
The error message says PostGraphile could not find the 'base' schema. This schema is created here at database initialization: https://github.com/ubisoft/mobydq/blob/master/db/init/00-database.sql#L5

On top of my head, this could mean two things:

1. Your database is not created properly on AWS so PostGraphile does not find the schema. Do you have a way to connect to the db and verify it's well created? You can check if there is data in the table base.parameter as inserting data there is one of the last operations done during db initialization.
Also there is no such thing as `\create mobydq` in the code. The PostgreSQL database is created automatically when starting the db container. Then every SQL file contained there is executed in order: https://github.com/ubisoft/mobydq/tree/master/db/init. You will notice at the beginning of each file they run `\connect mobydq`. I am not familiar with RDS on AWS but surely you need to adjust these files a bit to connect to your db and execute them.

2. The GraphQL API is not setup properly, maybe it's not pointing to your database on AWS in particular. Since you've not used the default configuration of this repo, you need to change the URI used by PostGraphile to connect to the db. This URI is setup in the .env file `GRAPHQL_DATABASE_URL=postgres://postgres:change_me@db:5432/mobydq`. You have to replace `db:5432` by the `host:port` of your db on AWS.

I would need a bit more details about how you setup the project on your side to help further. Also since this is not related to Docker-Openssl I'm going to close this issue and I invite you to create an issue on MobyDQ repository if you want to discuss this further.

Cheers
Alexis
